// Universal Export Utility for Excel (CSV) and PDF Printing

export const exportToCSV = (filename: string, headers: string[], rows: (string | number)[][]) => {
  const csvContent = [
    headers.join(','),
    ...rows.map(row =>
      row.map(cell => {
        const str = String(cell ?? '').replace(/"/g, '""');
        return `"${str}"`;
      }).join(',')
    )
  ].join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename}_${new Date().toISOString().split('T')[0]}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const exportToPDFPrint = (title: string, elementId?: string) => {
  if (elementId) {
    const element = document.getElementById(elementId);
    if (element) {
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(`
          <!DOCTYPE html>
          <html>
            <head>
              <title>${title}</title>
              <style>
                body { font-family: system-ui, -apple-system, sans-serif; padding: 20px; color: #0f172a; }
                h1 { font-size: 20px; font-weight: 800; border-bottom: 2px solid #6366f1; padding-bottom: 10px; margin-bottom: 20px; }
                table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 12px; }
                th, td { border: 1px solid #cbd5e1; padding: 8px 12px; text-align: left; }
                th { background-color: #f1f5f9; font-weight: 800; text-transform: uppercase; font-size: 10px; }
                .footer { margin-top: 30px; font-size: 10px; text-align: center; color: #64748b; border-top: 1px solid #e2e8f0; padding-top: 10px; }
              </style>
            </head>
            <body>
              <h1>${title} - Aichainz AIOS Report</h1>
              ${element.innerHTML}
              <div class="footer">Generated by Aichainz AIOS ERP · www.aichainz.com · ${new Date().toLocaleString('en-IN')}</div>
            </body>
          </html>
        `);
        printWindow.document.close();
        printWindow.focus();
        setTimeout(() => {
          printWindow.print();
          printWindow.close();
        }, 500);
        return;
      }
    }
  }
  window.print();
};
